# Generated by Django 6.0.6 on 2026-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
