# Generated by Django 6.0.6 on 2026-06-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_feedback_feedback_id_alter_query_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
